"""Legal case ORM model.

The platform's central business entity: every later module (documents, timeline,
hearings, reports, AI conversations, notifications) attaches to a case, so this
row is deliberately the *only* place a case's identity, lifecycle state, court
information, and assignments are recorded.

No authorization logic lives here. Whether a caller may use the case-management
capabilities is decided by :mod:`core.roles`; whether they may reach *this
particular* case is decided by :mod:`services.case_access`, which reads the two
assignment columns below.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from enum import StrEnum

from sqlalchemy import Date, DateTime, Enum, ForeignKey, String, Text, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.base import Base
from models.user import User


class CaseStatus(StrEnum):
    """Lifecycle state of a case, as specified by ``06-case-management.md``.

    The order of the members is the natural progression of a case, which is what
    :data:`~core.cases.STATUS_TRANSITIONS` encodes; it is *not* a ranking, and
    nothing sorts on it.

    :attr:`ARCHIVED` is also the soft-delete state — archiving a case never
    removes the row, because documents, timeline entries, and audit records all
    reference it. Archived cases stay searchable, as the spec requires.
    """

    #: Being prepared; not yet part of the active workload.
    DRAFT = "draft"
    #: Filed and active, but nobody has started work on it.
    OPEN = "open"
    #: Actively being worked on.
    IN_PROGRESS = "in_progress"
    #: Work is blocked until the next hearing takes place.
    WAITING_FOR_HEARING = "waiting_for_hearing"
    #: Concluded. May be reopened if the matter returns.
    CLOSED = "closed"
    #: Soft-deleted: retained and searchable, but out of the working set.
    ARCHIVED = "archived"


class CasePriority(StrEnum):
    """How urgently a case needs attention.

    Editable at any point in the lifecycle. Ordering is defined by
    :data:`~core.cases.PRIORITY_RANK` rather than by the member values, because
    sorting alphabetically would put "urgent" below "low".
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class Case(Base):
    """A legal case."""

    __tablename__ = "cases"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)

    # The human-facing identifier everyone quotes in correspondence. Unique and
    # indexed: it is looked up directly, searched, and sorted on. Generated by
    # `core.cases.build_case_number` when the client does not supply one.
    case_number: Mapped[str] = mapped_column(
        String(50), unique=True, index=True, nullable=False
    )

    title: Mapped[str] = mapped_column(String(255), nullable=False)

    # Free text and unbounded in practice, so `Text` rather than a capped
    # `String`: a case summary is prose, and truncating it would lose meaning.
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Free text rather than an enum, deliberately: the spec names the field but
    # defines no set of categories, and `ai-workflow-rules.md` forbids inventing
    # business behaviour. Promoting it to an enum later is a migration, not a
    # redesign.
    category: Mapped[str | None] = mapped_column(String(100), nullable=True)

    status: Mapped[CaseStatus] = mapped_column(
        Enum(
            CaseStatus,
            name="case_status",
            # Persist the enum *values* ("in_progress") rather than the Python
            # member names ("IN_PROGRESS"), matching how `user_role` is stored.
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        default=CaseStatus.DRAFT,
        server_default=CaseStatus.DRAFT.value,
        index=True,
    )

    priority: Mapped[CasePriority] = mapped_column(
        Enum(
            CasePriority,
            name="case_priority",
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        default=CasePriority.MEDIUM,
        server_default=CasePriority.MEDIUM.value,
        index=True,
    )

    court_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Calendar dates, not timestamps: a filing or a hearing happens on a day, and
    # storing an instant would make the value depend on the reader's timezone.
    filing_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    next_hearing_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # Assignments. Nullable because a draft case may not have anyone on it yet,
    # and because the spec requires "Remove Lawyer" / "Remove Representative".
    # ON DELETE SET NULL rather than CASCADE: users are soft-deleted, so this
    # only guards against manual cleanup — and losing a case because an account
    # was removed would be catastrophic.
    assigned_lawyer_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    assigned_court_representative_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )

    # Audit trail (`code-standards.md`: every sensitive operation is recorded).
    # Populated from the authenticated caller, never from the request body.
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # ------------------------------------------------------- relationships #
    #
    # Four foreign keys point at `users`, so every relationship must name the one
    # it uses — SQLAlchemy cannot guess.
    #
    # `selectin` rather than the default lazy load: the API returns the assignees'
    # and the auditors' *names* (an identifier alone is useless in a table), so
    # they are needed on every read. A lazy load would issue one query per case
    # per relationship — the classic N+1 — whereas `selectin` batches a whole page
    # into four extra queries regardless of its size, and cannot be forgotten at a
    # call site the way an explicit `joinedload` can.

    assigned_lawyer: Mapped[User | None] = relationship(
        "User", foreign_keys=[assigned_lawyer_id], lazy="selectin"
    )
    assigned_court_representative: Mapped[User | None] = relationship(
        "User", foreign_keys=[assigned_court_representative_id], lazy="selectin"
    )
    creator: Mapped[User | None] = relationship("User", foreign_keys=[created_by], lazy="selectin")
    updater: Mapped[User | None] = relationship("User", foreign_keys=[updated_by], lazy="selectin")

    # ------------------------------------------------------------- derived #

    @property
    def is_archived(self) -> bool:
        """Whether the case has been archived (soft-deleted)."""
        return self.status is CaseStatus.ARCHIVED

    def is_assigned_to(self, user_id: uuid.UUID) -> bool:
        """Whether this user is the assigned lawyer or court representative.

        The per-resource half of case authorization: a permission grants the
        *capability* to view cases, this decides *which* rows.
        """
        return user_id in (self.assigned_lawyer_id, self.assigned_court_representative_id)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        # Title and description are client-confidential; keep them out of reprs
        # and therefore out of any log line that interpolates a case.
        return f"<Case id={self.id!s} number={self.case_number!r} status={self.status.value!r}>"
