"""The Notification Service: the one place a notification is created.

``16-notifications.md`` asks for a *"centralized Notification Service"* that
subscribes to domain events, creates notifications, delivers them, marks them
read, and manages preferences — and requires that it *"remain independent from
business modules"*. This module is that service. The independence is a property
of the dependency graph rather than a convention: it holds a repository, an
:class:`~services.events.EventPublisher`, and a metrics recorder, and **not one
business service**. There is no path from here to a case, a document, or a
report that is not a read through :mod:`services.notification_recipients`.

The reverse direction is what actually matters, and it is stronger: **no business
module imports this file.** They publish domain events to a dispatcher that knows
no consumers; :mod:`services.notification_events` is registered on that
dispatcher in :mod:`core.lifespan`, one line beside the WebSocket manager. So
``code-standards.md``'s *"all notifications must be generated by the Notification
Service"* and the spec's *"business logic should never create notifications
directly"* are both true because there is no function a business module could
call, not because nobody has called one.

**Delivery goes back onto the event channel, and never near a socket.** The spec
requires that *"the Notification Service must never communicate directly with
clients"* and that *"all delivery should use the existing event infrastructure"*.
So this service persists a notification and then **publishes**
``notification.created`` on the recipient's own ``user:<id>`` topic — which the
connection manager already knows how to route and already authorizes, since a
user topic is identity equality. It holds an ``EventPublisher``, which has one
method and no way to reach a subscriber, a connection, or a client.

**Nothing here can fail a business operation.** Every path that runs on the
subscriber's thread catches its own exceptions, logs them, and counts them: the
change that produced the event committed long before this ran, so raising would
turn a successful upload into a 500 and invite a duplicating retry. That is the
same contract :meth:`~services.timeline.TimelineService.record` keeps and the
same one :meth:`~services.events.EventDispatcher.publish` keeps, applied one
layer further out.

**No notification content ever reaches a log.** There is none to reach one: a row
stores a rule key and a bounded context, and the logs here carry identifiers,
counts, rule keys, and categories only — never a rendered message, never a case
number, never a recipient's name. The same line ``code-standards.md`` draws for
OCR text, chunks, questions, answers, and report sections.
"""

from __future__ import annotations

import uuid
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

import structlog

from core.config import settings
from core.events import DomainEventType, user_topic
from core.exceptions import (
    NotificationNotFoundError,
    NotificationsDisabledError,
)
from core.notifications import (
    ANNOUNCEMENT_RULES,
    DEFAULT_PREFERENCES,
    AnnouncementKind,
    NotificationCategory,
    NotificationPreferenceKey,
    NotificationRule,
    NotificationTarget,
    dedupe_key,
    normalize_context,
    preference_from_value,
)
from models.notification import Notification
from models.user import User
from repositories.notification import (
    NotificationCounts,
    NotificationRepository,
    NotificationStatistics,
)
from schemas.notification import NotificationListQuery
from services.events import EventPublisher, NullEventPublisher
from services.notification_metrics import (
    NotificationFailureReason,
    NotificationMetricsRecorder,
    NotificationMetricsSnapshot,
    NullNotificationMetrics,
)

logger = structlog.get_logger(__name__)


@dataclass(frozen=True, slots=True)
class NotificationPage:
    """One page of a feed, together with the totals a client renders around it."""

    results: list[Notification]
    total: int
    counts: NotificationCounts
    page: int
    page_size: int


@dataclass(frozen=True, slots=True)
class AnnouncementOutcome:
    """What publishing one system announcement actually reached."""

    kind: AnnouncementKind
    recipients: int
    #: Active accounts that were not notified because they have switched system
    #: announcements off. Reported rather than hidden, so an administrator knows
    #: the difference between "nobody was told" and "nobody wanted to be".
    skipped: int


@dataclass(frozen=True, slots=True)
class NotificationMetrics:
    """The monitoring view's two halves, joined.

    Row counts come from SQL and are exact; delivery, latency, and failure come
    from the process and carry a ``since``. See
    :mod:`services.notification_metrics` for why that split is not an
    inconsistency.
    """

    statistics: NotificationStatistics
    counters: NotificationMetricsSnapshot
    pending: int
    enabled: bool
    window_days: int | None


class NotificationService:
    """Creates, delivers, reads, and configures notifications."""

    def __init__(
        self,
        notifications: NotificationRepository,
        *,
        events: EventPublisher | None = None,
        metrics: NotificationMetricsRecorder | None = None,
    ) -> None:
        self._notifications = notifications
        self._events = events or NullEventPublisher()
        self._metrics = metrics or NullNotificationMetrics()

    # --------------------------------------------------------------- create #

    def create(
        self,
        *,
        rule: NotificationRule,
        recipient_ids: Sequence[uuid.UUID],
        context: Mapping[str, Any] | None = None,
        case_id: uuid.UUID | None = None,
        actor_id: uuid.UUID | None = None,
        target: NotificationTarget | None = None,
        event_id: uuid.UUID | None = None,
        event_type: str | None = None,
        occurred_at: datetime | None = None,
        discriminator: str | None = None,
    ) -> list[Notification]:
        """Create one rule's notification for a batch of already-authorized people.

        **The single creation path**, used by the event subscriber and by system
        announcements alike, so preferences, duplicate suppression, persistence,
        delivery, and metrics are written once rather than once per caller.

        The recipients are assumed to have been authorized already — by
        :class:`~services.notification_recipients.NotificationRecipientResolver`
        for an event, or by "every active account" for an announcement. This
        method deliberately does **not** re-check: it holds no case repository
        and no access policy, so it *cannot*, which is what keeps authorization
        in one place rather than in two that can disagree.

        Four filters are applied in this order, and the order is the cheap-first
        one: the feature switch, then preferences (one query for the batch), then
        the two duplicate checks (one query each for the batch). A batch that
        empties at any stage costs nothing further.

        Returns:
            The notifications actually created, which may be fewer than the
            recipients asked for and may be none at all. Both are ordinary
            outcomes rather than failures.
        """
        if not settings.NOTIFICATIONS_ENABLED:
            return []
        if not recipient_ids:
            return []

        wanted = self._filter_by_preference(rule, recipient_ids)
        if not wanted:
            return []

        dedupe = dedupe_key(
            rule_key=rule.key,
            case_id=case_id,
            target=target,
            discriminator=discriminator,
        )
        wanted = self._filter_duplicates(wanted, event_id=event_id, dedupe=dedupe)
        if not wanted:
            return []

        stored_context = normalize_context(context)
        rows = [
            Notification(
                id=uuid.uuid4(),
                recipient_id=recipient_id,
                event_id=event_id,
                event_type=event_type,
                rule_key=rule.key,
                category=rule.category.value,
                notification_type=rule.notification_type,
                priority=rule.priority,
                context=dict(stored_context),
                case_id=case_id,
                actor_id=actor_id,
                target_type=target.target_type.value if target is not None else None,
                target_id=target.target_id if target is not None else None,
                dedupe_key=dedupe,
            )
            for recipient_id in wanted
        ]

        try:
            created = self._notifications.create_many(rows)
        except Exception:
            # The batch is all-or-nothing, so this is "nobody was told" rather
            # than "some were". Logged by rule and count — never the context,
            # which carries a case number.
            #
            # **The one expected cause is the unique constraint**, and when it
            # fires the outcome is already correct: two API processes handling
            # the same event have raced, one of them committed, and the recipient
            # has exactly one notification. Losing this batch is the constraint
            # doing its job, which is why it is recorded rather than retried — a
            # retry would re-collide, and the ordinary duplicate check
            # (`existing_event_recipients`) is what keeps this path rare in the
            # first place.
            self._notifications.rollback()
            self._metrics.record_failed(NotificationFailureReason.PERSISTENCE_FAILED)
            logger.exception(
                "notification_persistence_failed",
                rule=rule.key,
                category=rule.category.value,
                recipients=len(wanted),
            )
            return []

        # One observation per row, not one per batch: the metric is "notifications
        # created", and a case with three participants really did produce three.
        for _ in created:
            self._metrics.record_created(rule.key)

        logger.info(
            "notification_created",
            rule=rule.key,
            category=rule.category.value,
            notification_type=rule.notification_type.value,
            priority=rule.priority.value,
            recipients=len(created),
            event_type=event_type,
        )

        self._announce(created, occurred_at=occurred_at)
        return created

    def _filter_by_preference(
        self, rule: NotificationRule, recipient_ids: Sequence[uuid.UUID]
    ) -> list[uuid.UUID]:
        """Drop the people who have switched this kind of notification off.

        One query for the whole batch — the rule names exactly one preference
        key, so asking per person would make the cost of an event proportional to
        the size of the team it fans out to.

        An account with **no stored row** follows
        :data:`~core.notifications.DEFAULT_PREFERENCES` rather than being treated
        as opted out, which is what makes the platform's invariant ("every
        important event produces a notification for its authorized users") true
        for an account that has never opened the settings page.

        A failure here **admits** rather than excludes: a preference lookup that
        could not run is not evidence that somebody asked not to be told, and
        silently swallowing notifications because the database hiccuped is the
        worse of the two errors.
        """
        default = DEFAULT_PREFERENCES.get(rule.preference, True)
        try:
            stored = self._notifications.preferences_for_many(
                recipient_ids, preference_key=rule.preference.value
            )
        except Exception:  # pragma: no cover - defensive
            logger.exception("notification_preference_lookup_failed", rule=rule.key)
            return list(recipient_ids)

        wanted = [
            recipient_id
            for recipient_id in recipient_ids
            if stored.get(recipient_id, default)
        ]

        suppressed = len(recipient_ids) - len(wanted)
        if suppressed:
            self._metrics.record_suppressed(suppressed)
            logger.debug(
                "notification_suppressed_by_preference",
                rule=rule.key,
                preference=rule.preference.value,
                suppressed=suppressed,
            )
        return wanted

    def _filter_duplicates(
        self,
        recipient_ids: Sequence[uuid.UUID],
        *,
        event_id: uuid.UUID | None,
        dedupe: str,
    ) -> list[uuid.UUID]:
        """Drop the people who already have this notification.

        **Two checks, because they catch different things** — the split
        :func:`~core.notifications.dedupe_key` records:

        * the same *dispatched event*, which is exact and is also enforced by a
          unique index, so a race that slips past this check still cannot produce
          two rows;
        * the same *thing said*, within
          ``NOTIFICATION_DEDUPE_WINDOW_SECONDS``, which is what catches a retried
          worker or a double-click without silencing a case genuinely updated
          twice in a week.

        A failure here **admits** as well, and for the mirror of the preference
        reason: a duplicate is a small annoyance, and a missing notification about
        a hearing is not.
        """
        remaining = list(recipient_ids)

        if event_id is not None:
            try:
                already = self._notifications.existing_event_recipients(event_id, remaining)
            except Exception:  # pragma: no cover - defensive
                logger.exception("notification_duplicate_check_failed", check="event")
                already = set()
            remaining = [entry for entry in remaining if entry not in already]

        if remaining and settings.NOTIFICATION_DEDUPE_WINDOW_SECONDS > 0:
            since = datetime.now(UTC) - timedelta(
                seconds=settings.NOTIFICATION_DEDUPE_WINDOW_SECONDS
            )
            try:
                recent = self._notifications.recent_dedupe_recipients(
                    dedupe, remaining, since=since
                )
            except Exception:  # pragma: no cover - defensive
                logger.exception("notification_duplicate_check_failed", check="window")
                recent = set()
            remaining = [entry for entry in remaining if entry not in recent]

        skipped = len(recipient_ids) - len(remaining)
        if skipped:
            self._metrics.record_deduplicated(skipped)
            logger.debug("notification_deduplicated", suppressed=skipped)
        return remaining

    # -------------------------------------------------------------- deliver #

    def _announce(
        self, notifications: Sequence[Notification], *, occurred_at: datetime | None
    ) -> None:
        """Publish each notification onto its recipient's own topic.

        **This is the whole of "real-time delivery"**, and it is deliberately
        three lines of publishing rather than anything that knows what a socket
        is. The connection manager routes a ``user:<id>`` topic to the
        connections that authenticated as that account, and a user topic is
        authorized by identity equality — so a notification cannot be delivered
        to anyone but its recipient even if this method were wrong about who it
        was for.

        The payload carries **identifiers, a category, a type, and a priority,
        and no wording at all**. The client refetches through the API that
        authorizes the read, which is the rule
        ``15-real-time-synchronization.md`` established for every other event —
        and here it also means a notification's text never travels on a channel,
        which is one fewer place for it to be logged by something in between.

        Failures are counted and swallowed. The notification is already
        persisted, so a client that missed the announcement sees it on its next
        poll or its next page load: late rather than lost, which is the trade
        every part of this platform makes for a channel nothing depends on.
        """
        for notification in notifications:
            try:
                published = self._events.publish(
                    event_type=DomainEventType.NOTIFICATION_CREATED,
                    topic=user_topic(notification.recipient_id),
                    case_id=notification.case_id,
                    actor_id=notification.actor_id,
                    payload={
                        "notification_id": notification.id,
                        "category": notification.category,
                        "notification_type": notification.notification_type.value,
                        "priority": notification.priority.value,
                        "rule_key": notification.rule_key,
                        "target_type": notification.target_type,
                        "target_id": notification.target_id,
                    },
                )
            except Exception:  # pragma: no cover - the dispatcher never raises
                published = None

            if published is None:
                self._metrics.record_failed(NotificationFailureReason.DELIVERY_FAILED)
                continue

            # Measured from the **originating** event rather than from this
            # publication: what an operator wants to know is how long it took the
            # platform to tell somebody after the thing happened, and measuring
            # from the moment the notification was built would exclude the queue
            # wait that is the only part likely to be slow.
            reference = occurred_at or notification.created_at
            self._metrics.record_delivered(
                latency_ms=max(0.0, (datetime.now(UTC) - _aware(reference)).total_seconds())
                * 1000.0
            )

    # --------------------------------------------------------------- reading #

    def list_notifications(
        self, query: NotificationListQuery, *, actor: User
    ) -> NotificationPage:
        """Return one page of the caller's own feed, with their unread state.

        **Only the caller's.** The scope is applied in the database query, so the
        page totals count only their notifications — a total that included other
        people's would disclose how many exist, and the spec requires history to
        remain user-specific.

        The counts come back with the page because the panel that renders one
        also draws the badge, and making it ask twice would be two round trips to
        render one popover.
        """
        results, total = self._notifications.list_notifications(query, recipient_id=actor.id)
        counts = self._notifications.counts(
            recipient_id=actor.id, unread_cap=settings.NOTIFICATION_UNREAD_COUNT_CAP
        )
        return NotificationPage(
            results=results,
            total=total,
            counts=counts,
            page=query.page,
            page_size=query.page_size,
        )

    def get_notification(self, notification_id: uuid.UUID, *, actor: User) -> Notification:
        """Return one of the caller's notifications.

        Raises:
            NotificationNotFoundError: it does not exist, it was archived, or it
                belongs to somebody else. The three are deliberately
                indistinguishable — see the exception for why.
        """
        notification = self._notifications.get(notification_id, recipient_id=actor.id)
        if notification is None:
            logger.info(
                "notification_lookup_failed",
                notification_id=str(notification_id),
                user_id=str(actor.id),
            )
            raise NotificationNotFoundError
        return notification

    def summary(self, *, actor: User) -> NotificationCounts:
        """The caller's unread state, for the bell.

        Its own method rather than a field on the list, because the bell needs it
        on every page of the application and the list does not: fetching a page
        of notifications to draw a badge would download a feed nobody opened.
        """
        return self._notifications.counts(
            recipient_id=actor.id, unread_cap=settings.NOTIFICATION_UNREAD_COUNT_CAP
        )

    # ----------------------------------------------------------- read state #

    def mark_read(self, notification_ids: Sequence[uuid.UUID], *, actor: User) -> int:
        """Mark specific notifications as read. Returns how many changed.

        **Identifiers that are not the caller's are ignored rather than
        refused.** A panel marks what it has on screen, and one row archived or
        already read underneath it must not fail the whole request — and refusing
        would also confirm that a notification with that identifier exists, which
        is the disclosure this feature avoids everywhere else.
        """
        changed = self._notifications.mark_read(notification_ids, recipient_id=actor.id)
        if changed:
            logger.info("notification_read", user_id=str(actor.id), count=changed)
            self._announce_read(actor, count=changed)
        return changed

    def mark_all_read(
        self, *, actor: User, category: NotificationCategory | None = None
    ) -> int:
        """Mark every unread notification as read. Returns how many changed.

        The category filter exists because a feed filtered to one category beside
        a "mark all as read" button that ignored the filter is the most reliable
        way to lose a notification somebody meant to keep.
        """
        changed = self._notifications.mark_all_read(
            recipient_id=actor.id, category=category.value if category else None
        )
        if changed:
            logger.info(
                "notification_read_all",
                user_id=str(actor.id),
                count=changed,
                category=category.value if category else None,
            )
            self._announce_read(actor, count=changed)
        return changed

    def _announce_read(self, actor: User, *, count: int) -> None:
        """Tell the reader's other tabs that their unread count moved.

        On their own topic and nobody else's, so this discloses nothing: what a
        person has read is between them and their own browser windows. Published
        rather than pushed, for the same reason everything else here is — the
        service does not know what a socket is.
        """
        self._events.publish(
            event_type=DomainEventType.NOTIFICATION_READ,
            topic=user_topic(actor.id),
            actor_id=actor.id,
            payload={"count": count},
        )

    # ---------------------------------------------------------- preferences #

    def preferences(self, *, actor: User) -> dict[NotificationPreferenceKey, tuple[bool, bool]]:
        """The caller's answer to every preference the platform offers.

        Returns:
            ``key → (in_app, is_default)``. The **complete** set rather than only
            the stored rows, so a settings page renders from one response and a
            preference added later appears automatically at its default — and so
            a client never has to know that "no row" means "the default".
        """
        stored = self._notifications.preferences_for(actor.id)
        return {
            key: (
                stored.get(key.value, DEFAULT_PREFERENCES.get(key, True)),
                key.value not in stored,
            )
            for key in NotificationPreferenceKey
        }

    def update_preferences(
        self, values: Mapping[NotificationPreferenceKey, bool], *, actor: User
    ) -> dict[NotificationPreferenceKey, tuple[bool, bool]]:
        """Store the caller's choices and return the complete set.

        Only the keys supplied are written; anything omitted keeps its current
        value, which is what lets two settings panels open at once avoid silently
        reverting each other.
        """
        self._notifications.set_preferences(
            actor.id, {key.value: enabled for key, enabled in values.items()}
        )
        logger.info(
            "notification_preferences_updated",
            user_id=str(actor.id),
            # The **keys** and how many changed, never a map of what somebody
            # switched off: which notifications a person has silenced is a small
            # statement about how they work.
            keys=sorted(key.value for key in values),
        )
        return self.preferences(actor=actor)

    # -------------------------------------------------------- announcements #

    def announce(
        self, *, kind: AnnouncementKind, message: str, actor: User
    ) -> AnnouncementOutcome:
        """Publish a platform-wide announcement or maintenance notice.

        **The one path that creates a notification from a person rather than from
        an event**, and the reason is structural: :mod:`core.events` defines no
        broadcast scope, because every event the platform carries is about
        something somebody owns and a scope with no owner is a scope with no
        authorization rule. See the note above
        :data:`~core.notifications.ANNOUNCEMENT_RULES`.

        It is still the Notification Service creating the notification — no
        business module is involved at all — and everything downstream is the
        ordinary path: preferences are honoured, duplicates are suppressed, rows
        are batched, and each one is announced on its recipient's own topic.

        Recipients are written in batches of
        ``NOTIFICATION_ANNOUNCEMENT_BATCH_SIZE`` rather than in one statement,
        because this is the only path whose fan-out is the size of the platform
        and a single insert of every account would hold one transaction open for
        all of it.

        Raises:
            NotificationsDisabledError: creation is switched off on this
                deployment. Refused rather than silently doing nothing, because
                unlike an event — which nobody is waiting on — an administrator
                pressed a button and is entitled to know it had no effect.
        """
        if not settings.NOTIFICATIONS_ENABLED:
            raise NotificationsDisabledError

        rule = ANNOUNCEMENT_RULES[kind]
        recipients = self._notifications.active_recipient_ids()

        created = 0
        batch_size = settings.NOTIFICATION_ANNOUNCEMENT_BATCH_SIZE
        for start in range(0, len(recipients), batch_size):
            batch = recipients[start : start + batch_size]
            created += len(
                self.create(
                    rule=rule,
                    recipient_ids=batch,
                    context={"message": message},
                    actor_id=actor.id,
                    # Every announcement is its own notification even when the
                    # wording repeats: a maintenance window announced twice is
                    # two windows, and suppressing the second would silence the
                    # one that mattered. The discriminator is what makes the
                    # windowed duplicate check see them as different.
                    discriminator=str(uuid.uuid4()),
                )
            )

        logger.info(
            "notification_announcement_published",
            kind=kind.value,
            actor_id=str(actor.id),
            # Counts and the kind. **Never the message**: an announcement is
            # written by a person and could say anything, and this module's rule
            # is that no notification content reaches a log.
            recipients=created,
            candidates=len(recipients),
        )

        return AnnouncementOutcome(
            kind=kind, recipients=created, skipped=max(0, len(recipients) - created)
        )

    # ----------------------------------------------------------- monitoring #

    def metrics(
        self, *, window_days: int | None = None, pending: int = 0
    ) -> NotificationMetrics:
        """Return platform-wide notification health.

        Args:
            window_days: apply a window to the **SQL** figures. The in-process
                counters have their own window — the process's lifetime — which
                is reported as ``since`` rather than pretending the two are the
                same thing.
            pending: events accepted and not yet turned into notifications, read
                from the subscriber rather than counted here. A gauge read from
                the thing that owns the queue cannot drift, which is the same
                reasoning
                :meth:`~websocket.manager.ConnectionManager.metrics_snapshot`
                records for its connection count.
        """
        since = (
            datetime.now(UTC) - timedelta(days=window_days) if window_days is not None else None
        )
        return NotificationMetrics(
            statistics=self._notifications.statistics(since=since),
            counters=self._metrics.snapshot(),
            pending=max(0, pending),
            enabled=settings.NOTIFICATIONS_ENABLED,
            window_days=window_days,
        )


def _aware(value: datetime) -> datetime:
    """Read a timestamp as UTC-aware.

    SQLite returns naive datetimes for a ``TIMESTAMP WITH TIME ZONE`` column, so
    a latency computed against one would raise rather than be slightly wrong.
    Assumed UTC because that is what every timestamp on this platform is written
    as.
    """
    return value if value.tzinfo is not None else value.replace(tzinfo=UTC)


def resolve_preference_keys(stored: Mapping[str, bool]) -> dict[NotificationPreferenceKey, bool]:
    """Read stored preference rows into the keys this version defines.

    Rows whose key this version does not know are dropped rather than raising —
    the registry is open by design, and a key written by a later version of the
    platform must not make an earlier one unable to load somebody's settings.
    """
    resolved: dict[NotificationPreferenceKey, bool] = {}
    for raw_key, enabled in stored.items():
        key = preference_from_value(raw_key)
        if key is not None:
            resolved[key] = enabled
    return resolved


__all__ = [
    "AnnouncementOutcome",
    "NotificationMetrics",
    "NotificationPage",
    "NotificationService",
    "resolve_preference_keys",
]
