"""The background report-generation worker.

The one place that knows both halves of the picture: it builds a
:class:`~services.report.ReportService` for a job and hands it to a queue.
Keeping it separate from both is what lets :mod:`services.job_queue` stay
ignorant of the service (it is injected a callable) and :mod:`services.report`
stay ignorant of the queue's implementation (it is injected a protocol) — neither
imports the other, so there is no cycle to work around with a deferred import.
The same shape as :mod:`services.ocr_worker` and :mod:`services.indexing_worker`.

**Each job gets its own database session.** A worker runs on a background thread
long after the request that queued it has returned, and a SQLAlchemy ``Session``
is not thread-safe — reusing the request's session would be a use-after-free with
extra steps. The session is opened here, per job, and closed in a ``finally``, so
a connection cannot leak however the run ends.

**The provider, the prompt library, and the embedding model are *not* per job.**
Each is process-wide for reasons its own module records — an HTTP connection
pool, a compiled-template cache, and a model measured in gigabytes — and the
report service reaches all three through :class:`~services.rag.RagService`, which
is built here from the same shared instances a request would get.

**A report is the platform's slowest background job by a wide margin**, and that
is the reason this pool exists separately from the OCR and indexing ones rather
than being folded into either. A seven-section report is seven pipeline runs:
seven query embeddings, seven vector searches, and seven calls to a metered
language model. Sharing a pool with extraction would make one report delay every
upload's text; sharing one with indexing would make a single re-index of a
900-page bundle delay every report. They fail differently, they are sized
differently, and they compete for different resources.

The service the worker builds is deliberately given a
:class:`~services.job_queue.NullJobQueue`: a job must not be able to enqueue more
work, which is what would turn a bug into an unbounded loop — and here, into an
unbounded bill.
"""

from __future__ import annotations

import structlog
from sqlalchemy.orm import Session

from core.config import settings
from db.session import SessionLocal
from repositories.case import CaseRepository
from repositories.document import DocumentRepository
from repositories.report import ReportRepository
from repositories.search import SearchRepository
from repositories.timeline import TimelineRepository
from services.embedding import get_embedder
from services.job_queue import NullJobQueue, ThreadPoolJobQueue
from services.llm import get_llm_provider
from services.prompts import get_prompt_library
from services.rag import RagService
from services.rag_metrics import get_rag_metrics
from services.report import ReportJob, ReportService
from services.search import SearchService
from services.search_metrics import get_search_metrics
from services.search_ranking import get_ranker
from services.timeline import TimelineService
from services.vector_search import get_vector_searcher

logger = structlog.get_logger(__name__)


def _rag_service(session: Session) -> RagService:
    """Build the pipeline a report's sections are produced by.

    Assembled here rather than injected, because a background thread has no
    request to resolve dependencies from — but assembled from **exactly the same
    collaborators** ``api.deps.get_rag_service`` uses, which is what makes a
    section generated by a worker identical to one generated by a request.

    The load-bearing line is the same one that function records: the pipeline is
    given a :class:`~services.search.SearchService` and nothing else that could
    reach a passage. A worker that built the pipeline with a raw vector searcher
    would be a background path around the case scope, which is the one way this
    feature's authorization could be undone without anybody editing a policy.
    """
    search = SearchService(
        SearchRepository(session),
        DocumentRepository(session),
        CaseRepository(session),
        get_embedder(),
        get_vector_searcher(),
        get_ranker(),
        metrics=get_search_metrics(),
    )
    return RagService(
        search, get_prompt_library(), get_llm_provider(), metrics=get_rag_metrics()
    )


def run_report_job(job: ReportJob) -> None:
    """Process one queued report on its own session.

    Never raises: :meth:`~services.report.ReportService.process` records every
    failure as a ``failed`` run, and the queue catches anything that escapes even
    that.
    """
    session = SessionLocal()
    try:
        timeline = TimelineService(TimelineRepository(session), CaseRepository(session))

        service = ReportService(
            ReportRepository(session),
            CaseRepository(session),
            _rag_service(session),
            # A worker may not queue more work — see the module docstring.
            NullJobQueue(name="reports"),
            timeline=timeline,
        )
        service.process(job)
    finally:
        session.close()


#: The application's report queue.
#:
#: A module-level singleton because the pool it owns is a process-wide resource:
#: one pool of ``REPORT_WORKER_CONCURRENCY`` threads, shared by every request
#: that asks for a report, is the whole point of bounding it. Started and stopped
#: by the application lifespan (see :mod:`core.lifespan`); a queue that was never
#: started still works, because :meth:`ThreadPoolJobQueue.enqueue` starts it on
#: first use.
#:
#: **One worker by default**, unlike OCR's two, and the reason is the model
#: rather than the CPU: a report is a burst of calls to a metered, rate-limited
#: API, and a second worker doubles the rate at which a free-tier key is
#: exhausted without making any single report finish sooner.
report_queue: ThreadPoolJobQueue[ReportJob] = ThreadPoolJobQueue(
    run_report_job,
    max_workers=settings.REPORT_WORKER_CONCURRENCY,
    name="reports",
)


def start_report_workers() -> None:
    """Start the worker pool and recover work stranded by a previous process.

    The requeue is the half that matters: a job's schedule lives in memory but
    its *record* lives in the database, so a restart leaves ``pending`` rows that
    nothing would ever pick up — and unlike a stalled index, a stalled report is
    something a user is actively watching a progress bar for. Re-queueing is safe
    to repeat: the claim is atomic, so a job queued twice still processes once.

    Neither half is allowed to abort startup. An API that refused to come up
    because its report pool could not be created would take down authentication,
    cases, and documents over a background feature — the same contract
    :func:`~services.indexing_worker.start_index_workers` keeps.
    """
    if not settings.REPORTS_ENABLED:
        logger.info("report_workers_disabled")
        return

    try:
        report_queue.start()
    except Exception:
        logger.exception("report_workers_start_failed")
        return

    session = SessionLocal()
    try:
        service = ReportService(
            ReportRepository(session),
            CaseRepository(session),
            _rag_service(session),
            queue=report_queue,
        )
        service.requeue_pending()
    except Exception:
        logger.exception("report_requeue_failed")
    finally:
        session.close()


def stop_report_workers() -> None:
    """Drain the worker pool on shutdown.

    Draining rather than cancelling: a run stopped mid-generation leaves its row
    at ``processing``, and that is the one state no other worker will claim. It
    can take a while — a report in flight is waiting on a language model — which
    is the cost of not stranding a run a user is watching.
    """
    report_queue.shutdown(wait=True)


__all__ = [
    "report_queue",
    "run_report_job",
    "start_report_workers",
    "stop_report_workers",
]
